pipeline:
  backend:
    image: chef/chefdk:2.5.8
    commands:
      - chef exec berks install
      - chef exec cookstyle
      - chef exec foodcritic . -X spec -f any
      - chef exec rspec -P spec/**/*_spec.rb --tty --color
      - echo chef exec kitchen test --destory always
