pipeline:
  Build:
    image: chef/chefdk:2.5.8
    commands:
      - chef exec berks install

  Cookstyle:
    image: chef/chefdk:2.5.8
    group: lint
    commands:
      - chef exec cookstyle
  Foodcritic:
    image: chef/chefdk:2.5.8
    group: lint
    commands:
      - chef exec foodcritic . -X spec -f any
  Rspec:
    image: chef/chefdk:2.5.8
    group: lint
    commands:
      - chef exec rspec -P spec/**/*_spec.rb --tty --color
  kitchen-test-ubuntu-1604:
    image: chef/chefdk:2.5.8
    # group: kitchen-test
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - whoami
      - apt-get update
      - apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - apt-get update
      - apt-get install -y docker-ce
      - sleep 5
      - chef exec kitchen test default-ubuntu-1604
  kitchen-test-ubuntu-1404:
    image: chef/chefdk:2.5.8
    # group: kitchen-test
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - whoami
      - apt-get update
      - apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - apt-get update
      - apt-get install -y docker-ce
      - sleep 5
      - chef exec kitchen test default-ubuntu-1404
  kitchen-test-centos-7:
    image: chef/chefdk:2.5.8
    # group: kitchen-test
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - whoami
      - apt-get update
      - apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - apt-get update
      - apt-get install -y docker-ce
      - sleep 5
      - chef exec kitchen test default-centos-7
  kitchen-test-centos-6:
    image: chef/chefdk:2.5.8
    # group: kitchen-test
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - whoami
      - apt-get update
      - apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - apt-get update
      - apt-get install -y docker-ce
      - sleep 5
      - chef exec kitchen test default-centos-6

services:
  docker:
    image: docker:18.04.0-ce-dind
    privileged: true
    command: [ --storage-driver=overlay2]
