pipeline:
  Build:
    image: chef/chefdk:2.5.8
    commands:
      - chef exec berks install
  Cookstyle:
    image: chef/chefdk:2.5.8
    group: lint
    commands:
      - chef exec cookstyle
  Foodcritic:
    image: chef/chefdk:2.5.8
    group: lint
    commands:
      - chef exec foodcritic . -X spec -f any
  Rspec:
    image: chef/chefdk:2.5.8
    group: lint
    commands:
      - chef exec rspec -P spec/**/*_spec.rb --tty --color
  kitchen-test:
    #image: chef/chefdk:2.5.8
    image: docker:18.04.0-ce-dind
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - whoami
      - apt-get update
      - curl -L https://www.opscode.com/chef/install.sh | bash -s -- -P chefdk
      - echo chef exec kitchen test --destory always

services:
  docker:
    image: docker:18.04.0-ce-dind
    environment:
    command: [ --storage-driver=overlay2]
