version: 2
jobs:
  build:
    docker:
      - image: chef/chefdk:2.5.8
    steps:
      - checkout
      - run:
          name: Berkshelf Install
          command: chef exec berks install
      - run:
          name: Chef Cookstyle
          command: chef exec cookstyle
      - run:
          name: Chef Foodcritic
          command: chef exec foodcritic . -X spec -f any
      - run:
          name: Chefspec
          command: chef exec rspec -P spec/**/*_spec.rb --tty --color
      - run:
          name: Kitchen-ci
          command: echo chef exec kitchen test --destory always
